language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator10.3

env:
  global:
  - WORKSPACE=SparkSDK.xcworkspace
  - SCHEME=SparkSDK
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s"      CONFIGURATION="ReleaseTest" IsIntegrationTestingTask="true"
    - DESTINATION="OS=10.3,name=iPhone 6s plus"  CONFIGURATION="ReleaseTest"
    - DESTINATION="OS=11.0,name=iPhone 7"      CONFIGURATION="ReleaseTest"
    - DESTINATION="OS=11.1,name=iPhone 7" CONFIGURATION="ReleaseTest"
    - DESTINATION="OS=11.2,name=iPhone 7 plus"      CONFIGURATION="ReleaseTest"
before_install:
  - gem install cocoapods --pre
  - pod repo update > /dev/null
  - brew install sendemail
script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration "$CONFIGURATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clientSecret="$CLIENTSECRET" test | xcpretty -c
  - travis_wait 50 bash IntegrationTesting.sh
branches:
