language: objective-c
osx_image: xcode9.3
#xcode_project: SparkSDK.xcodeproj
#xcode_scheme: ReleaseTest
#xcode_sdk: iphonesimulator11.3

env:
  global:
  - WORKSPACE=SparkSDK.xcworkspace
  - SCHEME=SparkSDK
  matrix:
    - DESTINATION="name=iPhone 6,OS=10.0"      CONFIGURATION="ReleaseTest" IsIntegrationTestingTask="true"
    - DESTINATION="name=iPhone 6s plus,OS=10.1"  CONFIGURATION="ReleaseTest"
    - DESTINATION="name=iPhone 7,OS=10.2"      CONFIGURATION="ReleaseTest"
    - DESTINATION="name=iPhone 7,OS=10.3.1" CONFIGURATION="ReleaseTest"
    - DESTINATION="name=iPhone 7 plus,OS=11.0"      CONFIGURATION="ReleaseTest"
before_install:
#  - gem install cocoapods --pre
#  - pod repo update > /dev/null
#  - brew install sendemail
- brew update
- brew outdated carthage || brew upgrade carthage
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod repo update
script:
- xctool clean build -workspace SparkSDK.xcworkspace -scheme SparkSDK -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace SparkSDK.xcworkspace -scheme SparkSDK -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7 plus,OS=11.0' | xcpretty

#  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration "$CONFIGURATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clientSecret="$CLIENTSECRET" test | xcpretty -c
#  - travis_wait 50 bash IntegrationTesting.sh
branches:
