language: objective-c
osx_image: xcode9.3
xcode_project: SparkSDK.xcodeproj
xcode_scheme: ReleaseTest
xcode_sdk: iphonesimulator11.3

env:
  global:
  - WORKSPACE=SparkSDK.xcworkspace
  - SCHEME=SparkSDK
  matrix:
    - DESTINATION="name=iPhone 6,OS=10.0"      CONFIGURATION="ReleaseTest" IsIntegrationTestingTask="true"
    - DESTINATION="name=iPhone 6s plus,OS=10.1"  CONFIGURATION="ReleaseTest"
    - DESTINATION="name=iPhone 7,OS=10.2"      CONFIGURATION="ReleaseTest"
    - DESTINATION="name=iPhone 7,OS=10.3.1" CONFIGURATION="ReleaseTest"
    - DESTINATION="name=iPhone 7 plus,OS=11.0"      CONFIGURATION="ReleaseTest"
before_install:
  - gem install cocoapods --pre
  - pod repo update > /dev/null
  - brew install sendemail
script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration "$CONFIGURATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clientSecret="$CLIENTSECRET" test | xcpretty -c
  - travis_wait 50 bash IntegrationTesting.sh
branches:
